---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cprportal-web-v1
  namespace: cprportal-dev
  labels:
    app: cprportal-web
    version: v1
    auth: cprportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cprportal-web
      version: v1
  template:
    metadata:
      labels:
        app: cprportal-web
        version: v1
        auth: cprportal
    spec:
      serviceAccountName: cprportal-api
      containers:
      - name: cprportal-web
        image: docker-registry.umusic.com/cprportal/cprportal-web:v0.0.1
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
      imagePullSecrets:
      - name: regcred
