---
apiVersion: v1
kind: Service
metadata:
  name: cp3-web
  namespace: cp3-dev
  labels:
    app: cp3-web
spec:
  type: ClusterIP
  selector:
    app: cp3-web
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 80
