---
apiVersion: v1
kind: Service
metadata:
  name: cprportal-web
  namespace: cprportal-dev
  labels:
    app: cprportal-web
spec:
  type: ClusterIP
  selector:
    app: cprportal-web
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 80
